
-- 1. Create helper function to check admin status (if not exists)
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- 2. Create banners table
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  link text,
  active boolean default true,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.banners enable row level security;

-- 4. Create Policies (Drop first to avoid conflicts if re-running)
drop policy if exists "Public banners are viewable by everyone" on public.banners;
drop policy if exists "Admins can insert banners" on public.banners;
drop policy if exists "Admins can update banners" on public.banners;
drop policy if exists "Admins can delete banners" on public.banners;

create policy "Public banners are viewable by everyone"
  on public.banners for select
  using ( true );

create policy "Admins can insert banners"
  on public.banners for insert
  with check ( auth.role() = 'service_role' or public.is_admin() );

create policy "Admins can update banners"
  on public.banners for update
  using ( auth.role() = 'service_role' or public.is_admin() );

create policy "Admins can delete banners"
  on public.banners for delete
  using ( auth.role() = 'service_role' or public.is_admin() );

-- 5. Insert initial data (only if empty)
do $$
begin
  if not exists (select 1 from public.banners limit 1) then
    insert into public.banners (title, image_url, display_order)
    values 
    ('Churrasco Premium', 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&q=80&w=1600', 1),
    ('Sabor Inigualável', 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&q=80&w=1600', 2),
    ('Cortes Selecionados', 'https://images.unsplash.com/photo-1544025162-d76690b67f66?auto=format&fit=crop&q=80&w=1600', 3);
  end if;
end $$;
