-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  category text not null,
  image text, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create Policy: Everyone can view products
create policy "Public products are viewable by everyone"
  on products for select
  using ( true );

-- Create Policy: Only authenticated users can insert/update/delete
create policy "Authenticated users can modify products"
  on products
  for all
  using ( auth.role() = 'authenticated' );

-- Note: You need to create a storage bucket named 'product-images' in the dashboard.
