
-- 1. Create Products Table (if not exists)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  category text not null,
  image text, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Create Orders Table (if not exists)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  payment_method text not null,
  total numeric not null,
  items jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create Profiles Table (if not exists)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Enable RLS on all tables
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.profiles enable row level security;

-- 5. Policies for Products
create policy "Public products are viewable by everyone" on products for select using ( true );
create policy "Authenticated users can modify products" on products for all using ( auth.role() = 'authenticated' );

-- 6. Policies for Orders
-- Allow anyone to create an order
create policy "Enable insert for everyone" on public.orders for insert with check (true);
-- Allow users to see their own orders (we will add user_id column next)
create policy "Users can see their own orders" on orders for select using ( auth.uid() = user_id );

-- 7. Policies for Profiles
create policy "Public profiles are potentially viewable by everyone" on profiles for select using ( true );
create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );

-- 8. Add user_id to Orders table
-- This command is safe to run multiple times because of 'if not exists'
alter table public.orders 
add column if not exists user_id uuid references auth.users(id);

-- 9. Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'customer');
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid error when recreating
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 10. Insert Initial Products Data
insert into public.products (title, description, price, category, image)
values 
('Kit Churrasco Completo', 'O kit ideal para seu churrasco! Contém: 1kg de Picanha Premium, 1kg de Linguiça Artesanal, 1kg de Asa de Frango Temperada, 1pct de Carvão 4kg e 1 Sal de Parrilla.', 249.90, 'carne', 'https://placehold.co/600x400/2a2a2a/D4AF37?text=Kit+Churrasco'),
('Carvão Premium 4kg', 'Carvão de eucalipto selecionado, acendimento rápido e brasa duradoura.', 24.90, 'insumos', 'https://placehold.co/600x400/121212/D4AF37?text=Carvão'),
('Sal de Parrilla com Ervas', 'Tempero ideal para cortes grossos, garante salga uniforme.', 18.50, 'insumos', 'https://placehold.co/600x400/121212/D4AF37?text=Sal+Parrilla'),
('Tábua Rústica de Madeira', 'Tábua artesanal de madeira nobre, perfeita para servir seu churrasco.', 119.90, 'acessorios', 'https://placehold.co/600x400/3e2723/D4AF37?text=Tábua+Rústica'),
('Faca do Chef 8"', 'Faca em aço inox com fio de alta precisão.', 89.90, 'acessorios', 'https://placehold.co/600x400/3e2723/D4AF37?text=Faca+Chef');
