-- Script Seguro de Configuração (Safe Setup)
-- Este script remove políticas antigas antes de criar novas para evitar erros de duplicidade.

-- 1. TABELAS (Cria se não existirem)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  category text not null,
  image text, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  payment_method text not null,
  total numeric not null,
  items jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Adicionar user_id em orders se não existir
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name='orders' and column_name='user_id') then
        alter table public.orders add column user_id uuid references auth.users(id);
    end if;
end $$;

-- 2. SEGURANÇA (RLS)
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.profiles enable row level security;

-- 3. LIMPEZA DE POLÍTICAS ANTIGAS (Para evitar erro 42710)
drop policy if exists "Public products are viewable by everyone" on products;
drop policy if exists "Authenticated users can modify products" on products;
drop policy if exists "Enable insert for everyone" on orders;
drop policy if exists "Users can see their own orders" on orders;
drop policy if exists "Public profiles are potentially viewable by everyone" on profiles;
drop policy if exists "Users can update own profile" on profiles;

-- 4. CRIAÇÃO DE NOVAS POLÍTICAS
-- Produtos
create policy "Public products are viewable by everyone" on products for select using ( true );
create policy "Authenticated users can modify products" on products for all using ( auth.role() = 'authenticated' );

-- Pedidos
create policy "Enable insert for everyone" on public.orders for insert with check (true);
create policy "Users can see their own orders" on orders for select using ( auth.uid() = user_id );

-- Perfis
create policy "Public profiles are potentially viewable by everyone" on profiles for select using ( true );
create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );

-- 5. AUTOMATIZAÇÃO (Triggers)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'customer');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
