-- Execute this in your Supabase SQL Editor to enable order tracking

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  payment_method text not null,
  total numeric not null,
  items jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.orders enable row level security;

-- Allow anyone to create an order (public access for checkout)
create policy "Enable insert for everyone" 
on public.orders for insert 
with check (true);

-- Optional: Allow reading (e.g. for order status page later)
create policy "Enable read access for everyone"
on public.orders for select
using (true);
